5 create a button component
devhausleipzigacademy/camp10-midterm pull request #15
Opened 2023-06-30 10:19 UTC by radicalgraphical

2023-06-30 13:05 UTC, ReallyBoard123 requested changes
The code is almost there. Just a bit of clean up and abstracting the code to make it neat! But overall good job. You would also need to update the stories once you find the right settings for your button

2023-06-30 13:05 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +
and then you can even further abstract the tailwind CSS

const variantStyles: Record<ButtonVariant, string> = {
  primary: 'fill your values here',
  secondary: 'fill your values here',
};

same for const sizeStyles and abstract the styling

optional? but you could also put opacity-50 as disabledStyle

2023-06-30 13:05 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +    buttonPrimaryYellowSmall: "bg-yellow text-dark-light rounded font font-500 py-1  disabled:opacity-50",
then all these codes could be deleted, and the things from above be used as props here

2023-06-30 13:05 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +        "flex justify-center text-center text-s px-9 w-2 .w-full",
w-2 .w-full ?? these buttons will be very small in width

do you just want it to be w-full?

2023-06-30 13:05 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +    buttonPrimaryYellowDefault: "bg-yellow  text-dark-light rounded font font-700 py-4  disabled:opacity-50",
i think we have two different roundedness. On default it is 8px and on the small one it is 6px

2023-07-03 08:14 UTC, radicalgraphical commented
Hey shiraq , i pushed the updated button :)

2023-07-03 08:28 UTC, JanHendryk commented on src/components/Button.tsx
> +
Done!

2023-07-03 08:29 UTC, JanHendryk commented on src/components/Button.tsx
> +    buttonPrimaryYellowSmall: "bg-yellow text-dark-light rounded font font-500 py-1  disabled:opacity-50",
Yeah, done!

2023-07-03 08:30 UTC, JanHendryk commented on src/components/Button.tsx
> +type ButtonProps = {
Done, we changed it to a more abstract component

2023-07-03 11:53 UTC, ReallyBoard123 approved these changes

2023-07-03 11:53 UTC, merged