9 create genreicon component
devhausleipzigacademy/camp10-midterm pull request #25
Opened 2023-07-03 12:31 UTC by systm-spec

2023-07-03 13:26 UTC, systm-spec commented
Storybook fixed, rdy to review

2023-07-04 07:25 UTC, ReallyBoard123 requested changes
👍 It is so beautiful!

2023-07-04 07:25 UTC, ReallyBoard123 commented on src/components/GenreIcon.tsx
> +  variant?: 'default' | 'active';
Semantically, your genreIcon has an active state and a default state. The usage of variant here (however, works and is functional) is confusing as we will always switch between variants. 

But if you pass a prop called isActive? : boolean it will be easier

2023-07-04 07:25 UTC, ReallyBoard123 commented on src/components/GenreIcon.tsx
> +  variant = 'default',
similarly you can pass a default value here isActive = false,

2023-07-04 07:25 UTC, ReallyBoard123 commented on src/components/GenreIcon.tsx
> +  const styles: Record<typeof variant, string> = {
you wont need this then

2023-07-04 07:25 UTC, ReallyBoard123 commented on src/components/GenreIcon.tsx
> +        className={cn(
can pass the classes here with ternary
cn(
    'rounded-xl flex items-center justify-center h-14 w-14 text-[1.875rem]',
    isActive ? 'bg-white-dimmed' : 'bg-dark-light',
    className
  );

2023-07-04 07:25 UTC, ReallyBoard123 commented on src/libs/utils.ts
> +import { clsx, type ClassValue } from "clsx";
can you pull the main once? I think it is already there

2023-07-04 09:51 UTC, systm-spec commented
The requested changes were made, tested and are ready for beeing reviewed.

2023-07-04 10:00 UTC, ReallyBoard123 approved these changes

2023-07-04 10:02 UTC, merged