19 create bookingdetail component
devhausleipzigacademy/camp10-midterm pull request #28
Opened 2023-07-04 09:09 UTC by JanHendryk

We have completed our task. Thank you for your review!

2023-07-04 14:14 UTC, ReallyBoard123 requested changes

2023-07-04 14:14 UTC, ReallyBoard123 commented on src/components/BookingDetails.tsx
> +   variant?:"default"|"active"|"disabled",
it is semantically a better approach to see "active" and "disabled" as states, rather than seeing them as variants. Remember that the button only changes the state, rather than rendering a new button. 

So, think of isActive and isDisabled as a state. Check the code for genreIcon. It also takes an isActive state

2023-07-04 14:15 UTC, ReallyBoard123 commented
> We have completed our task. Thank you for your review!

pull the main before working, and run pnpm install

2023-07-05 08:16 UTC, systm-spec commented
The changes were made & tested, free for re-reviewing

2023-07-05 08:20 UTC, systm-spec commented
merged push

2023-07-06 07:37 UTC, ReallyBoard123 approved these changes

2023-07-06 07:37 UTC, merged