31 create movie detail page
devhausleipzigacademy/camp10-midterm pull request #43
Opened 2023-07-07 15:17 UTC by systm-spec

Ready for review

2023-07-10 07:53 UTC, ReallyBoard123 requested changes
I did not really look deeply into the tailwind styling yet, but the page overall looks great! There are some type errors I think. Sometimes the errors are only available in the console. Thus, having an extension that brings all the type errors in your editor itself helps!

2023-07-10 07:53 UTC, ReallyBoard123 commented on src/api/movies.ts
> +    `https://api.themoviedb.org/3/movie/${movieId}?api_key=830580354c9aaf7a57d3f02a7a0010ae`
never commit your apikey. Please store the API key in the .env file and use the readme from the project to see how to use it :)

2023-07-10 07:53 UTC, ReallyBoard123 commented on src/pages/MovieDetails.tsx
> +    genres,
genres have a type error here. Are you trying to use genre_ids?

2023-07-10 07:53 UTC, ReallyBoard123 commented on src/pages/MovieDetails.tsx
> +        setNovel(res.data.crew.find(x => x.job == 'Novel').name);
ummm, I think this has to be little more thoughtful? So the current problem is that the API is a little bit inconsistent. For many movies, it does have a writer - but sometimes available in the known_for_department == Writing. Then you can at least return one writer from there for sure!

2023-07-11 14:31 UTC, systm-spec commented on src/api/movies.ts
> +    `https://api.themoviedb.org/3/movie/${movieId}?api_key=830580354c9aaf7a57d3f02a7a0010ae`
Done

2023-07-11 14:32 UTC, systm-spec commented on src/pages/MovieDetails.tsx
> +    genres,
Reworked

2023-07-11 14:32 UTC, systm-spec commented on src/pages/MovieDetails.tsx
> +        setNovel(res.data.crew.find(x => x.job == 'Novel').name);
cleaned up, added extra case

2023-07-11 14:33 UTC, systm-spec commented
Ready for next review

2023-07-12 09:49 UTC, ReallyBoard123 requested changes
hey, somehow some of the layout issues persist :( I think some names are too long! and that breaks the page. I am sorry, but I did not think of this before. So names would have to be clipped! You would have to write a JS function for this.

try this link: http://localhost:5173/movies/569094
another one: http://localhost:5173/movies/575264

and the writer seems to be still missing here: http://localhost:5173/movies/667538

even though this is there in the response
{
      "adult": false,
      "gender": 2,
      "id": 74569,
      "known_for_department": "Writing",
      "name": "Joby Harold",
      "original_name": "Joby Harold",
      "popularity": 8.216,
      "profile_path": "/q3jMKt9f93fZwJHVQoov0hFAFwJ.jpg",
      "credit_id": "5e2f8fdcac8e6b0015bd5c86",
      "department": "Writing",
      "job": "Screenplay"
    },


I am sorry that the API is not a great one! But this is still a though experiment on how shitty it could be to fix these cases!

The page looks so good overall ❤️

2023-07-12 14:20 UTC, systm-spec commented
ready for next review

2023-07-13 08:46 UTC, ReallyBoard123 approved these changes

2023-07-13 08:46 UTC, merged