72 add movie ids and generate screenings in the database
devhausleipzigacademy/camp10-midterm pull request #75
Opened 2023-07-20 11:22 UTC by pswu11

- [ ] add movie and screening POST modules 
- [ ] ingest 30 movies and corresponding screenings (30 days, 8 timeslots per day) in the database

2023-07-24 12:32 UTC, ReallyBoard123 commented
> Perhaps, a nice-to-have issue would be to improve pagination on Movies where there are more than 5 pages, for now I just slicd it.

For camp9, they got rid of the paginations, and created an endless scroll effect

2023-07-24 12:49 UTC, pswu11 commented
> > Perhaps, a nice-to-have issue would be to improve pagination on Movies where there are more than 5 pages, for now I just slicd it.
> 
> For camp9, they got rid of the paginations, and created an endless scroll effect

also a good idea.

2023-07-25 08:36 UTC, ReallyBoard123 requested changes

2023-07-25 08:48 UTC, pswu11 commented on server/imports/importer.ts
> +import dotenv from 'dotenv';
@ReallyBoard123 `server/` is not a vite project

2023-07-25 11:35 UTC, pswu11 commented
@ReallyBoard123 

I made below changes to importer: 
- kept `dotenv` cuz according to Dan vite is more for frontend and for server dotenv is a good fit
- make bindings mutable (`let ...`) instead of `const` - since it's supposed to be mutable 
- increase the request size limit to 5mb for importing larger amount of screenings at once
- add unique constraints to prisma so no duplicated screenings are allowed

2023-07-26 08:19 UTC, ReallyBoard123 approved these changes
to my 👀 this seems good and working!
I wish there was a better senior looking into this for more refined comments!

2023-07-26 08:19 UTC, merged